[package]
name = "mirage-tank"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.89"
clap = { version = "4.5.18", features = ["derive"] }
image = "0.25.2"

[[bin]]
name = "tank"
path = "src/main.rs"

[profile.release]
opt-level = "s"
